import mongoose from 'mongoose'; import 'dotenv/config'; import User from './models/User.js'; import SupportCase from './models/SupportCase.js'; import Note from './models/Note.js'; import { config } from './config.js';
const cases = [
['Technical Issue','High','Frustrated','New','My internet router loses connection every evening. I rebooted it twice but the issue continues.','Customer needs reliable connection restored.'],
['Billing','Medium','Negative','In Review','I was charged twice for my monthly subscription and would like the duplicate charge refunded.','Customer requests a duplicate billing refund.'],
['Login','Low','Neutral','Resolved','I could not sign in after changing my password, but resetting it fixed the problem.','Customer wanted access to their account.'],
['Refund','Critical','Very Negative','New','My order never arrived and I need a refund today. I already contacted delivery support.','Customer requests immediate refund for missing order.'],
['Delivery','Medium','Positive','Closed','The package was delayed but has now arrived. I am calling to confirm no further action is needed.','Customer wants delivery confirmation.']
];
async function seed() { await mongoose.connect(config.mongoUri); await Note.deleteMany({}); await SupportCase.deleteMany({}); await User.deleteMany({ email: 'agent@voice2case.demo' }); const agent = await User.create({ name: 'Demo Support Agent', email: 'agent@voice2case.demo', password: 'Agent123!' }); for (const [category, priority, sentiment, status, transcript, issue] of cases) await SupportCase.create({ agent: agent._id, transcript, summary: issue, customerIssue: issue, customerIntent: 'Resolve the reported support issue', category, priority, sentiment, keyInformation: ['Details supplied by customer'], troubleshootingAttempted: transcript.includes('already') || transcript.includes('rebooted') ? ['Customer attempted troubleshooting'] : [], followUpRequired: status === 'Resolved' || status === 'Closed' ? 'Not provided' : 'Follow up with customer after action is completed', recommendedNextAction: 'Review the account and take the appropriate support action.', escalation: priority === 'Critical' ? 'Required' : priority === 'High' ? 'Recommended' : 'Not Required', requestedOutcome: issue, status }); console.log('Seeded agent@voice2case.demo / Agent123!'); await mongoose.disconnect(); }
seed().catch(error => { console.error(error); process.exit(1); });
